
VariantDir('build', 'src', duplicate=0)

env = Environment( PROJECT_NAME = 'limbctrl_tests'
                 , CCFLAGS      = ['-Wall' , '-Wextra']
#                , LIBS         = ['framework'],
                 , CPPPATH      = ['#src', '#../firmware']
                 , CXXFLAGS     = ['-std=c++0x']
                 )

tests = env.Program('run_tests', [ 'build/tests_main.cpp'
                                 , 'build/communication_tests.cpp'
                                 ])

